//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Year_Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Face
    {
        public int FaceID { get; set; }
        public string FaceName { get; set; }
        public int SpecialNumber { get; set; }
        public int RecNo { get; set; }
        public byte[] FaceImg { get; set; }
        public int Size { get; set; }
        public int ImgID { get; set; }
    
        public virtual Img Img { get; set; }
    }
}
